/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import java.awt.Color;
import java.time.LocalTime;

/**
 *
 * @author User
 */
public class ClockDisplay extends javax.swing.JFrame
{

    /**
     * Creates new form ClockDisplay
     */
    public ClockDisplay()
    {
        initComponents();
       
        
        Clock c1 = new Clock(LocalTime.now());
        Clock c2 = new Clock();
        Clock c3 = new Clock();
        
        plTimeRow1.add(c1);
        new Thread(c1).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        plDescription = new javax.swing.JPanel();
        plTime = new javax.swing.JPanel();
        plTimeRow1 = new javax.swing.JPanel();
        plImage = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 3));

        plDescription.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout plDescriptionLayout = new javax.swing.GroupLayout(plDescription);
        plDescription.setLayout(plDescriptionLayout);
        plDescriptionLayout.setHorizontalGroup(
            plDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );
        plDescriptionLayout.setVerticalGroup(
            plDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().add(plDescription);

        plTime.setBackground(new java.awt.Color(0, 0, 0));
        plTime.setLayout(new java.awt.GridLayout(3, 1));

        plTimeRow1.setBackground(new java.awt.Color(0, 0, 0));
        plTimeRow1.setLayout(new java.awt.GridLayout(1, 1));
        plTime.add(plTimeRow1);

        getContentPane().add(plTime);

        plImage.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout plImageLayout = new javax.swing.GroupLayout(plImage);
        plImage.setLayout(plImageLayout);
        plImageLayout.setHorizontalGroup(
            plImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );
        plImageLayout.setVerticalGroup(
            plImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().add(plImage);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(ClockDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(ClockDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(ClockDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(ClockDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new ClockDisplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel plDescription;
    private javax.swing.JPanel plImage;
    private javax.swing.JPanel plTime;
    private javax.swing.JPanel plTimeRow1;
    // End of variables declaration//GEN-END:variables
}
